spring:
  cloud:
    gateway:
      routes:
        - id: spring-security
          uri: http://localhost:2020  # Direct URI of your authentication service
          predicates:
            - Path=/auth/**
          filters:
            - name: AuthenticationFilter

server:
  port: 8888

application:
  name: API-GATEWAY

